---
# Configuration file for project

project:
components:
 - components.position
 - components.mesh_graphic
 - components.armature
 - components.cube_collider
 - components.sphere_collider
 - components.rigidbody
 - components.hinge_constraint
 - components.point_constraint